### PR TITLE
Snapshot

### PR DESCRIPTION
**Pull request by nikolakanacki**

### CODE REVIEW

**Comment by tjgq** [comment]
We'd definitely be interested in this. Would you be willing to make the following changes:

- Modify `takeSnaphsot` to take a single `options` object argument with a `quality` key. This way we won't break clients if we add more options in the future.
- If the `preserveDrawingBuffer` option isn't set for `WebGlStage`, throw `Error('WebGlStage: takeSnapshot requires the preserveDrawingBuffer option to be set')` instead of silently returning a blank image.
- Throw an error if the quality is set to something other than a number between 0 and 100. Leaving it undefined to signal a default value is okay, but make the default 75 rather than 50. For Flash, perform the validation in the Javascript code.
- Add a `CssStage.prototype.takeSnaphsot` method throwing an `Error('CssStage: takeSnapshot not implemented')`.

**Comment by nikolakanacki** [comment]
On it.

**Comment by nikolakanacki** [comment]
@tjgq I'm almost done with the changes proposed, but are we sure about the `preserveDrawingBuffer` WebGL context parameter? Because it's known to degrade performance on some platforms and GPUs, and the "silent blank page" is already handled by calling `this.render()` inside `takeSnapshot()` method, right before extracting the image data from the canvas (or at least it should be, it forces the buffer to fill up again). Since the actual render (when the buffers are drawn and (hopefully) swapped) takes place a lot more often then someone potentially invoking the execution of `takeSnapshot` method, are we sure it is the right way to go?

**Comment by nikolakanacki** [comment]
I could maybe check if `preserveDrawingBuffer` option is set, and if it is, not invoke the `render()` method right before `toDataURL()`, to avoid unnecessary performance hit.

**Comment by tjgq** [comment]
You're completely right, and I was wrong - `preserveDrawingBuffer` isn't necessary as long as you access the drawing buffer before control is passed to the graphics pipeline.

I think calling `render()` unconditionally before calling `toDataURL` is perfectly fine: taking a snapshot should be a rare event, so the performance impact is negligible. So you can essentially disregard my comment regarding `preserveDrawingBuffer`. Thanks!

**Comment by nikolakanacki** [comment]
No problems! Have you got a chance to look at the updated code? I think it successfully addresses the points discussed earlier.

**Comment by tjgq** [comment]
This looks great! Thanks for addressing the comments.

Minor nit - can you fix the if/for statements to look like

```
if (foo) {
  bar;
}
```

instead of ```if (foo) bar;```?

**Comment by nikolakanacki** [comment]
Will do.

**Comment by nikolakanacki** [comment]
Done.

**Pull request merged**
